---
title: "OB-Workspace"
author: "Olivier Binette"
date: '2020-01-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mapdata)
library(maps)
library(ggmap)
library(httr)
library(lubridate)
source("prettyplot.R")
library(gender) #install.packages("genderdata", repos="http://packages.ropensci.org")
```


## Data

```{r}
data <- read.csv("AB_NYC_2019.csv")

data <- data %>% 
  mutate(last_review = ymd(last_review)) %>% 
  mutate(months_inactive = as.numeric(ymd("2019-07-08") - last_review)/30.42) %>% 
  mutate(months_active = (number_of_reviews - reviews_per_month*months_inactive)/reviews_per_month) %>% 
  mutate(months_active = case_when(
    months_active >=1 ~ months_active, 
    months_active <1 ~ 1
  )) %>% 
  mutate(nrml_avg_reviews = case_when(
    reviews_per_month>0 ~ number_of_reviews/months_active,
    is.na(reviews_per_month) ~ 0))
```

## Maps

```{r}
register_google(key="AIzaSyDnqUXoVEle0J7gGGZQcdV5HQeQEGRlxLQ")
```

```{r}
map = GET("https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyDnqUXoVEle0J7gGGZQcdV5HQeQEGRlxLQ&center=40.711021996806984,-74.0226380913756&zoom=11&format=png&maptype=roadmap&style=element:geometry%7Ccolor:0xf5f5f5&style=element:labels%7Cvisibility:off&style=element:labels.icon%7Cvisibility:off&style=element:labels.text.fill%7Ccolor:0x616161&style=element:labels.text.stroke%7Ccolor:0xf5f5f5&style=feature:administrative.land_parcel%7Cvisibility:off&style=feature:administrative.land_parcel%7Celement:labels.text.fill%7Ccolor:0xbdbdbd&style=feature:administrative.neighborhood%7Cvisibility:off&style=feature:administrative.neighborhood%7Celement:geometry%7Cvisibility:off&style=feature:administrative.neighborhood%7Celement:geometry.fill%7Ccolor:0xff713d%7Cvisibility:off&style=feature:administrative.neighborhood%7Celement:geometry.stroke%7Cvisibility:off&style=feature:poi%7Celement:geometry%7Ccolor:0xeeeeee&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:poi.park%7Celement:geometry%7Ccolor:0xe5e5e5%7Cweight:8&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:poi.place_of_worship%7Cvisibility:off&style=feature:poi.place_of_worship%7Celement:geometry.fill%7Ccolor:0xe5e5e5%7Cvisibility:on%7Cweight:8&style=feature:road%7Cvisibility:off&style=feature:road%7Celement:geometry%7Ccolor:0xffffff&style=feature:road.arterial%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:road.highway%7Celement:geometry%7Ccolor:0xdadada&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:road.local%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:transit.line%7Celement:geometry%7Ccolor:0xe5e5e5&style=feature:transit.station%7Celement:geometry%7Ccolor:0xeeeeee&style=feature:water%7Cvisibility:on%7Cweight:8&style=feature:water%7Celement:geometry%7Ccolor:0xc9c9c9&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&size=480x360")
```

```{r}
map = get_map(c(left=-74.25, right=-73.5, bottom=40.49, top=41), 
              zoom=12,
              maptype = "toner-lite",
              color="bw")

map_coarse = get_stamenmap(c(left=-74.25, right=-73.5, bottom=40.49, top=41), 
              zoom=10,
              maptype="terrain-background",
              #maptype="toner-background",
              color="bw", force=TRUE)
```


```{r}
library(RColorBrewer)
ggmap(map_coarse) +
  geom_point(data=data, aes(x=longitude, y=latitude), 
             size=0.1, alpha=0.5,
             color="black") +
  stat_density2d(data=data, aes(x=longitude, y=latitude,
                                fill=..level.., alpha=..level..), 
                 geom="polygon") +
  guides(alpha = FALSE, fill=FALSE) +
  scale_fill_gradient((brewer.pal(7, "Spectral"))) +
  xlim(-74.15, -73.7) +
  ylim(40.55, 40.91) +
  theme_void()
```


## Subway entrances

```{r}
library(stringr)

subways = read.csv("subways.csv")
subways = subways[,"the_geom"] %>% 
  str_remove_all("POINT ") %>% 
  str_remove_all("[\\(\\)]") %>% 
  str_split(" ")

subways = sapply(subways, function(x) {
  c(as.numeric(x[[1]]), as.numeric(x[[2]]))
})
```

```{r}
library(geosphere)

dat = data

lambd <- Vectorize(function(long, lat) {
  min(apply(subways, 2, function(s) {
    #distHaversine(c(long, lat), c(s[1], s[2]))
    x = lat - s[2]
    y = (long - s[1]) * cos((lat + s[2])*0.00872664626)  
    111.319 * sqrt(x*x + y*y) * 1000
  }))
})

dists = lambd(dat$longitude, dat$latitude)
```

## Other plots

```{r}
dists = readRDS("dists_to_subway.rds")
host_names = data[,"host_name", drop=F] %>% mutate(name = as.character(host_name))
genders = gender(unique(host_names$name))
genders = data.frame(name = genders$name, 
                gender = case_when(genders$proportion_female > 0.90 ~ "Female",
                    genders$proportion_female > 0.10 ~ "Unknown",
                    TRUE ~ "Male")
)

dat = data %>% mutate(genders=
                        sapply(as.character(data$host_name), function(x) {
                          i = which(genders$name == x)
                          if (length(i) > 0){
                            return(genders[i[1],]$gender)
                          }
                          return("Unkown")
                        }))
```

```{r}
dat = dat %>% mutate(dists=dists)
```

```{r}
d = dat %>% filter(room_type == "Private room", price < 500)
plot(d[,c("dists", "price", "nrml_avg_reviews", "availability_365")], axes=F, col=factor(d$genders))
```






```{r}
dat %>% 
  filter(price < 500) %>% 
  ggplot(aes(x=price, color=genders)) + 
  geom_density(bw=10) +
  facet_wrap(vars(room_type))
```




```{r}
dat %>% 
  filter(price < 500) %>% 
  ggplot(aes(x=price, color=room_type)) + 
  geom_density(bw=2)
```



```{r}
dat %>% filter(price==300 | price==299) %>% select(price, nrml_avg_reviews) %>% group_by(price) %>% summarize(median(nrml_avg_reviews))
```

```{r}
dat %>% filter(price==200 | price==199) %>% select(price, nrml_avg_reviews) %>% group_by(price) %>% summarize(median(nrml_avg_reviews))
```






```{r}
d = dat %>% filter(price < 500, room_type == "Private room", minimum_nights==1)

plot(log(d$dists), log(d$nrml_avg_reviews*d$price), col=factor(d$genders))
```







